services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI_USERS=mongodb+srv://cmarrom:5H67xhmzVNv3BXPy@cluster0.0qlkh.mongodb.net/users?retryWrites=true&w=majority
      - MONGO_URI_PRODUCTS=mongodb+srv://cmarrom:5H67xhmzVNv3BXPy@cluster0.0qlkh.mongodb.net/products?retryWrites=true&w=majority
      - JWT_SECRET=pass_secreta_xd
      - ADMIN_PASSWORD=admin_password
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions

volumes:
  mongo-data:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions: